name: Daily Server Ping

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  # Allows manual triggering
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up server and trigger API call
        run: |
          curl -X GET https://simple-server-pt.onrender.com/wake-up 